name: "@riiid/icons 업데이트"

on:
  push:
    branches: ["master"]
    paths: ["libraries/icons/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: cache node modules
        id: cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

      - name: generate component
        run: yarn generate
      
      - name: build typescript
        run: yarn build:typescript
      
      - name: copy package.json
        run: yarn build:copy

      - name: upload lib
        uses: actions/upload-artifact@v1.0.0
        with:
          name: lib
          path: lib

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: download lib
        uses: actions/download-artifact@v1.0.0
        with:
          name: lib

      - name: publish package
        run: yarn release:lib
