name: Sync figma icons

on:
  push:
    branches: [ master ]

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set npm token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      
      - name: set env
        run: echo FIGMA_TOKEN="${{ secrets.FIGMA_TOKEN }}" > .env

      # - name: cache node modules
      #   uses: actions/cache@v1
      #   with:
      #     path: node_modules
      #     key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-build-
      #       ${{ runner.OS }}-

      # - run: echo ${{ hashFiles('svgs/info.json') }}

      - name: install dependencies
        run: yarn

      - name: check new version
        id: version
        run: echo "##[set-output name=hasNewVersion]$(yarn -s check-new-version)"
        # run: yarn check-new-version

      - name: 'true'
        if: steps.version.outputs.hasNewversion == 'true'
        run: echo TRUE

      - name: 'false'
        if: steps.version.outputs.hasNewversion == 'false'
        run: echo F

  # fetch:
  #   needs: init
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2


