name: ABC

on:
  pull_request:
    branches:
      - master
      - figma/abc
      - 'figma/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.npm }}" >> ~/.npmrc
          yarn
          yarn lint || exit 0
          git commit --amend --no-edit "."
