name: ABC

on:
  pull_request:
    branches:
      - master
      - figma/abc
      - 'figma/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.npm }}" >> ~/.npmrc
      - run: yarn
      - run: yarn lint
#     - uses: actions/checkout@v2
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
