name: ABC

on:
  pull_request:
    branches:
      - 'figma/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: figma/abc

      - name: Setup
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.npm }}" >> ~/.npmrc
          yarn
      - name: Lint
        run: yarn lint || exit 0
        
      - name: Commit changes
        run: |
          git config user.name "Figma Plugin"
          git config user.email ""
          git commit -am "lint"
      - uses: ad-m/github-push-action@v0.5.0
        with:
          branch: figma/abc
          github_token: ${{ secrets.github }}
