name: Publish

on:
  pull_request:
    types: closed
    branches: master

jobs:
  A:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir test
      - run: echo abcde >> test/test.txt
      - uses: actions/upload-artifact@v1
        with:
          name: test
          path: test
  B:
    needs: A
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: test
          path: test
      - run: ls -al
      - run: ls test
