name: Publish

on:
  pull_request:
    types: closed
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: github.event.pull_request.merged == true
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.npm }}" >> ~/.npmrc
          yarn
          yarn build
          yarn publish --non-interactive